 sudo: required
services:
  - docker

 before_install:
   - docker build -t mustafa1987/the-docker-react -f Dockerfile.dev .

 script:
   - docker run -e CI=true mustafa1987/the-docker-react npm run test